export const OUTGOING_ACTION_COOLDOWN_MS = 24 * 60 * 60 * 1000;


export const MINIMUM_WITHDRAW_INCOME = Number(
  process.env.NEXT_PUBLIC_MINIMUM_WIDTHDRAW_INCOME
);


export const MAXIMUM_WITHDRAW_INCOME = Number(
  process.env.NEXT_PUBLIC_MAXIMUM_WIDTHDRAW_INCOME
);


export const MINIMUM_SHARE_INCOME = Number(
  process.env.NEXT_PUBLIC_MINIMUM_SHARE_INCOME
);


export const MAXIMUM_SHARE_INCOME = Number(
  process.env.NEXT_PUBLIC_MAXIMUM_SHARE_INCOME
);